spring.application.name=eduBridgeHCM
spring.datasource.url=jdbc:${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=${DB_LOCAL_URL}
#spring.datasource.username=${DB_LOCAL_USER}
#spring.datasource.password=${DB_LOCAL_PASS}
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_nationalized_character_data=true
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.locale=vi_VN
jwt.secret-key=${JWT_SECRET:Vn5m9Qy0gq3W0v6q8Y9Q9qk8F7m2cR7Xq3Z3gYk5H2lK9sJp6WzF5bYp1eT8uKxN4cP2rL6vA9mQ7dS3tH8nJ5wR0xB2cF6}
#1 day
jwt.expiration.access-token=${ACCESS_EXPIRE:86400000}
#7 days
jwt.expiration.refresh-token=${REFRESH_EXPIRE:604800000}
#server.type=${SERVER_URL}
server.type=${LOCAL_URL}