spring.application.name=eduBridgeHCM
spring.datasource.url=jdbc:${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=${DB_LOCAL_URL}
#spring.datasource.username=${DB_LOCAL_USER}
#spring.datasource.password=${DB_LOCAL_PASS}
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_nationalized_character_data=true
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.locale=vi_VN
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
jwt.secret-key=${JWT_SECRET}
#1 day
jwt.expiration.access-token=${ACCESS_EXPIRE}
#7 days
jwt.expiration.refresh-token=${REFRESH_EXPIRE}
vnp.tmn-code=${VNP_TMN_CODE:ZDT0KK8Q}
vnp.hash-secret=${VNP_HASH_SECRET:0ANJ6LZDK4J3HX20MU176DGK5J19D5WV}
supabase.url=${SUPABASE_URL}
supabase.bucket.name=${SUPABASE_BUCKET_NAME}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}

