package com.sp26se041.edubridgehcm.enums;

public enum NotificationEventType {
    SCHOOL_POST_PUBLISHED,
    ADMIN_POST_PUBLISHED,
    NEW_USER_REGISTERED,
    BUY_PACKAGE_FEE,
    CREATE_PACKAGE_FEE,
    FAVORITE_SCHOOL,
    REMOVE_FAVORITE_SCHOOL,
    // Consultation flow
    CONSULTATION_BOOKED,
    CONSULTATION_CONFIRMED,
    CONSULTATION_CANCELLED,
    CONSULTATION_COMPLETED,
    CONSULTATION_NO_SHOW,
    // Counsellor slot assignment
    COUNSELLOR_SLOT_ASSIGNED,
    COUNSELLOR_SLOT_UNASSIGNED,

    // Admission reservation form
    RESERVATION_PENDING,
    RESERVATION_APPROVAL,
    RESERVATION_PAYMENT_PENDING,
    RESERVATION_PAYMENT_REJECTED,
    RESERVATION_DEPOSITED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLED,
    RESERVATION_REJECTED

}
